name: Deploy on Tag with Image Retention (Self-Hosted Runner)

on:
  push:
    tags:
      - '[0-9]*.[0-9]*' # Matches tags like 0.1, 1.2, etc.

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          IMAGE_NAME=glpi-react-img
          CONTAINER_NAME=glpi-react-container
          
          # Stop and remove the old container
          docker ps -a -q --filter "name=$CONTAINER_NAME" | xargs -r docker rm -f

          # Remove older images beyond the retention limit (keep 2 older + current)
          docker images $IMAGE_NAME --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" | \
          sort -rk 2 | \
          awk 'NR>3 {print $1}' | xargs -r docker rmi -f

          # Build the new image
          docker build -t $IMAGE_NAME:${GITHUB_REF_NAME} .

          # Start the new container
          docker compose up -d
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
