name: Deploy to Local Server

on:
  push:
    branches:
      - main  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner on the same machine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Application
      run: |
        mkdir -p /home/glpi/glpi_react
        rsync -avz --exclude='.git/' ./ /home/glpi/glpi_react/